/*
 Quantcast measurement tag
 Copyright (c) 2008-2017, Quantcast Corp.
*/
window.__qc=function(b){if(b.__qc)return b.__qc;var l=b.document,z=b.navigator,B="4dcfa7079941 127fdf7967f31 588ab9292a3f 32f92b0727e5 22f9aa38dfd3 a4abfe8f3e04 18b66bc1325c 958e70ea2f28 bdbf0cb4bbb 65118a0d557 40a1d9db1864 18ae3d985046 3b26460f55d".split(" "),N=!1,t=0,n=[],D=[],u=[],Ba={tcYgbCswcTSeq:1,"01-0VIaSjnOLg":1,aD1qr93XuF6aC:1,"56WJ0KtIxWJ_2":1,T1nhLcmCjVzQS:1,zddNYNtUkUhdQ:1,"59TntzuqummDw":1,P7x87XHnVfbWr:1,HGAVM7nQJ_sep:1,"w9vzus-GKCA0U":1,"00TsOkvHvnsZU":1,effSsmMYCbAck:1,PFW5FesqXn206:1,
"0dYLvhSGGqUWo":1,c1rF4kxgLUzNc:1,"5brKQLtleyIQU":1,"mEzuYq24VEJ-3":1,"57OGVHgSOoedo":1,"e7wR0qsM6-pDa":1,"8tgFhCTDYhV2V":1,"82MbSinIaQJw2":1,buQ2dAnrdTGCS:1,"49SVsgIZlUqPk":1,eeFYJkotb1rUU:1,EzVU5HfAMVqEV:1,"45nh8QKbsf2Xk":1,sLJ2v5QaN4z2Y:1,"5cvC4NOeGmtNA":1,"573scDfDoUH6o":1,"915Y6SMHQQJHI":1,z0zMG4nCgXzzj:1,"124BfeS-bwiSE":1,"ZzStSGgW6hG-4":1,KUMT4fYgcdEeg:1,d9vfr8QTWnv1E:1,fug7wP0GuN1h6:1,cd12aNCzw_ZaB:1,"51zXP5Cc9sxvQ":1,"4dIM5nVs2rFio":1,"8fZNjMQsH1Ews":1,C6W3aFrWFMS7m:1,N7ekbgK3G3jrt:1,dfQGRefil9mes:1,
"9axVJDmh4EHIM":1,NPcfSf1E0V1T1:1,"72V4-XKpaKDrE":1,"8cV3w6ZJH0sXI":1,sHwqAaPHqVjee:1,b15U9CAASyBMc:1},y=[],E={},H=0,I=[],F=null,X={},x={},ia=null,q,Y=[].slice,ja,Z,O,k,A,$,P,ka,la,ma,J,aa,Q,R,na,K,oa,pa,qa,ra,v,sa,C,S,ta,ba,ua,va,ca,s,wa,da,T,U,xa,ya,V,za,ea,fa,Aa,ga,G,L,M,W,ha,w=function(a){try{return{init:R,hash:Q,rules:xa,hasRules:V,defaults:Aa,__qc:function(){return!0}}[a].apply(null,Y.call(arguments,1))}catch(c){return!1}};w.evts=0;w.v=2;w.SD=B;w.qpixelsent=[];U=function(a){var c=a?a.length||
0:0,d;for(d=0;d<c;d++)if(!a[d])return!1;return!0};fa=function(a){(a=a||b._qacct)&&(ca(y,a)||y.push(a))};ca=function(a,c){var d=a.length,e;for(e=0;e<d;e++)if(a[e]===c)return!0;return!1};da=function(a){return{}.toString.call(a).match(/\s([a-zA-Z]+)/)[1].toLowerCase()};T=function(a){var c,d;c=da(a);if("array"===c)return a.slice(0);if("object"===c){c={};for(d in a)a.hasOwnProperty(d)&&(c[d]=a[d]);return c}return"string"===c?""+a:a};V=function(a){return ca(u,a)};Aa=function(a,c){var d;a&&((d=X[a])&&(c=
W(c,d)),c.qacct&&delete c.qacct,X[a]=c)};ga=function(a){var c,d;if(k(a))for(c in a)if("string"==typeof a[c]){c=a.event||"load";d=a.media||"webpage";"rule"!==c&&"load"!==c||"webpage"!==d&&"ad"!==d?v(a):(d=a.qacct||b._qacct,a.qacct=d,c=(c=x[d])?W(c,a):a,x[d]=c);fa(a.qacct);break}else"object"==typeof a[c]&&null!=a[c]&&ga(a[c])};W=function(a,c){var d={};d.qacct=a.qacct||c.qacct;d.event="load"===a.event||"load"===c.event?"load":a.event&&c.event?a.event||c.event:null;d.media=null;d.media="webpage"===a.media||
"webpage"===c.media?"webpage":"ad"===a.media||"ad"===c.media?"ad":a.media||c.media;ba(d,a,c);ba(d,c,a);d.event||delete d.event;d.media||delete d.media;return d};ba=function(a,c,d){var e,b,h,r,t,m;for(e in c)c.hasOwnProperty(e)&&!a.hasOwnProperty(e)&&(b=c[e],h=d[e],r="",t=!!b&&"string"==typeof b,m=!!h&&"string"==typeof h,t&&(r=b),t&&m&&(r+=","),m&&(r+=h),a[e]=r)};G=function(){var a=[],c,d;if(!(0<H)){wa();for(c in x)x.hasOwnProperty(c)&&x[c]&&(d=x[c],a.push(d),delete x[c]);1==a.length&&v(a[0]);1<a.length&&
v(a)}};L=function(a){var c=[],d,b;for(d=0;d<a.length;d++)b=a[d],Ba.hasOwnProperty(b.substring(2))?E[b]=5:V(b)||c.push(b);if(0===c.length)G();else for(d=0;d<c.length;d++)b=c[d],u.push(b),ua(b)};va=function(){for(var a;I[0]&&("loaded"==I[0].readyState||"complete"==I[0].readyState);)a=I.shift(),a.onreadystatechange=null,F.parentNode.insertBefore(a,F),M()};ua=function(a){var c,d;c=("https:"===l.location.protocol?"https://":"http://")+"rules.quantcount.com/rules-"+a+".js";F=F||l.scripts[0];H++;d=l.createElement("script");
"async"in d?(d.src=c,d.async=!1,d.onload=function(){E[a]=0;M()},d.onerror=function(){E[a]=1;M()},F.parentNode.insertBefore(d,F)):d.readyState?(E[a]=2,I.push(d),d.onreadystatechange=va,d.src=c):(E[a]=4,M())};M=function(){H-=0<H?1:0;G()};xa=function(){var a=!0,c,d,b;if(arguments.length){b=function(c){a?ga(c):v(c,!0)};for(c=0;c<arguments.length;c++)d=Y.call(arguments[c],0),d.splice(1,0,b),ya.apply(null,d);a=!1;N&&G()}};ya=function(a,c){var d=[],b=[],g=c||v,h,r,t,m,p;if((h=Y.call(arguments,2))&&h.length){r=
h[0]||U;t=h[1];m=h[2];h=m.length;for(p=0;p<h;p++)d.push(!1),b.push(null);d={p:a,f:d,r:r,c:m,a:t,v:b};V(a)||u.push(a);D.push(d);za(d,g)}};za=function(a,c){var d=a?a.c?a.c.length:0:0,b;for(b=0;b<d;b++)(function(d){var b,e;try{b=a.c[d][0],e=a.c[d].slice(1),e.splice(0,0,function(b){a.f[d]=!0;a.v[d]=b;ea(a,c)}),b.apply(null,e)}catch(t){a.f[d]=!0,a.v[d]=!1,ea(a,c)}})(b)};ea=function(a,c){var d=a.a,b=a.v,g=a.r||U,h,t,k,m,p,f;(h=U(a.f))&&(h=h&&g(b));if(h)for(b=0;b<d.length;b++)try{t=d[b][0];k=1<d[b].length?
d[b].slice(1):[];k=k.concat(a.v);m=t.apply(null,k);p={qacct:a.p,event:"rule"};for(f in m)m.hasOwnProperty(f)&&"qacct"!==f&&(p[f]=m[f]);c(p)}catch(n){}};ja=function(){return Z(0)!==Z(6)?1:0};Z=function(a){a=new Date(2E3,a,1,0,0,0,0);var c=a.toGMTString(),c=new Date(c.substring(0,c.lastIndexOf(" ")-1));return a-c};O=function(a){return a.replace(/\./g,"%2E").replace(/,/g,"%2C")};A="function"===typeof encodeURIComponent?encodeURIComponent:O;k=function(a){return"undefined"!=typeof a&&null!=a};$=function(){return Math.round(2147483647*
Math.random())};P=function(a){var c="",d=l.cookie,b;if(!d)return c;b=d.indexOf(a+"\x3d");a=b+a.length+1;-1<b&&(c=d.indexOf(";",a),0>c&&(c=d.length),c=d.substring(a,c));return c};ka=function(){var a="",c=J(),d,b,g;if(1===t)return";fpan\x3du;fpa\x3d";d=Q(c);for(b=0;b<B.length;b++)if(B[b]===d)return";fpan\x3du;fpa\x3d";d=new Date;b=P("__qca");if(0<b.length){try{g=+b.split("-")[2],338688E5<d-g&&(l.cookie=["__qca\x3d",b,"; expires\x3d",(new Date(g+338688E5)).toGMTString(),"; path\x3d/; domain\x3d",c].join(""))}catch(h){}a+=
";fpan\x3d0;fpa\x3d"+b}0===P("__qca").length&&(b="P0-"+$()+"-"+d.getTime(),l.cookie=["__qca\x3d",b,"; expires\x3d",(new Date(d.getTime()+338688E5)).toGMTString(),"; path\x3d/; domain\x3d",c].join(""),b=P("__qca"),a=0<b.length?a+(";fpan\x3d1;fpa\x3d"+b):a+";fpan\x3du;fpa\x3d");return a};la=function(a){l.cookie=a+"\x3d; expires\x3dThu, 01 Jan 1970 00:00:01 GMT; path\x3d/; domain\x3d"+J()};J=function(){var a,c,b,e;a=l.domain;"www."===a.substring(0,4)&&(a=a.substring(4,a.length));c=a.split(".");e=c.length;
if(3>e)return a;b=c[e-1];return 3>b.length?a:a=c[e-2]+"."+b};aa=function(a,c){var b;for(b=0;b<c.length;b++)a^=c.charCodeAt(b),a+=(a<<1)+(a<<4)+(a<<7)+(a<<8)+(a<<24);return a};Q=function(a){var c;c=aa(2166136261,a);a=aa(3386659096,a);return Math.round(Math.abs(c*a)/65536).toString(16)};S=function(a,c,d){var e="",g=b._qacct,h=null,r="webpage",n="load",m={},p,f,g=c?c.qacct||b._qacct:b._qacct;p=x[g];c?p&&(c=W(c,p)):c=p;g&&delete x[g];if(null!=c)for(f in c)m[f]=!0,c.hasOwnProperty(f)&&"string"===typeof f&&
"string"===typeof c[f]&&("uid"===f||"uh"===f?(na()||(h=Q(c[f])),delete c[f]):"qacct"!==f&&(0<c[f].length?e+=";"+f+a+"\x3d"+A(c[f]):m[f]=!1,"media"===f&&(r=c[f]),"event"===f&&(n=c[f])));if("string"!==typeof g){if(!k(b._qacct)||0===b._qacct.length)return"";g=b._qacct}if(g&&(p=X[g]))for(f in p)"string"===typeof f&&p.hasOwnProperty(f)&&!m[f]&&(e+=";"+f+a+"\x3d"+A(p[f]),"media"===f&&(r=p[f]),"event"===f&&(n=p[f]));m=E[g];k(m)||(m=3);e+=";rf"+a+"\x3d"+m;"string"===typeof h&&(c.uh=h,e+=";uh"+a+"\x3d"+A(h));
if("webpage"===r&&"load"===n){for(c=0;c<w.qpixelsent.length;c++)if(w.qpixelsent[c]===g&&!d)return"";w.qpixelsent.push(g)}"ad"===r&&(t=1);return";a"+a+"\x3d"+g+e};ta=function(){var a=l.getElementsByTagName("meta"),c="",b,e,g,h;for(b=0;b<a.length;b++){g=a[b];if(1E3<=c.length)return c;k(g)&&k(g.attributes)&&k(g.attributes.property)&&k(g.attributes.property.value)&&k(g.content)&&(e=g.attributes.property.value,g=g.content,3<e.length&&"og:"===e.substring(0,3)&&(0<c.length&&(c+=","),h=80<g.length?80:g.length,
c+=O(e.substring(3,e.length))+"."+O(g.substring(0,h))))}return A(c)};ma=function(a){return"object"===typeof a?["p","approved"===a.consent?"a":"d","asserted"===a.source?"e":"i"].join(""):""};na=function(){var a=!1;k(b.external)&&(a=b.external,a="function"===typeof a.InPrivateFilteringEnabled&&!0===a.InPrivateFilteringEnabled());return a||"1"==z.doNotTrack||"yes"===z.doNotTrack||"1"==z.msDoNotTrack};v=function(a,c){var d="function"===typeof encodeURIComponent?"n":"s",e=$(),g="",h="",r="",D="",m="",
p="u",f="1",s=0,u=[],q,v,x,y;t=0;k(w.qpixelsent)||(w.qpixelsent=[]);if(k(a))for(q in a)if("string"==typeof a[q]){h=S("",a,c);break}else"object"==typeof a[q]&&null!=a[q]&&(++s,h+=S("."+s,a[q],c));else"string"===typeof _qacct&&(h=S("",null,c));0!==h.length&&(s=z.cookieEnabled?"1":"0","undefined"!=typeof z.javaEnabled&&(p=z.javaEnabled()?"1":"0"),k(b._qmeta)&&(r=";m\x3d"+A(b._qmeta),b._qmeta=null),self.screen&&(g=screen.width+"x"+screen.height+"x"+screen.colorDepth),v=new Date,x=ja(),y=ka(),b.location&&
b.location.href&&(D=A(b.location.href)),l&&l.referrer&&(m=A(l.referrer)),b.self===b.top&&(f="0"),q=ta(),u.push("/pixel;r\x3d"+e+h+y+";ns\x3d"+f+";ce\x3d"+s),u.push(";je\x3d"+p+";sr\x3d"+g+";enc\x3d"+d+";dst\x3d"+x+";et\x3d"+v.getTime()+";tzo\x3d"+v.getTimezoneOffset()+r+";ref\x3d"+m+";url\x3d"+D+";ogl\x3d"+q),n.push(u),C())};sa=function(a){var c=new Image;a=[b.location.protocol,"//pixel.",oa(q)?"quantserve.com":"quantcount.com",a[0],";cm\x3d",ma(q),a[1]].join("");c.alt="";c.src=a;c.onload=function(){c&&
"number"==typeof c.width&&3===c.width&&la("__qca")}};C=function(){if(q)for(;n.length;)sa(n.shift());else ra()};oa=function(a){return!0===a||1===a||1===a||k(a)&&"approved"===a.consent?!0:!1};ra=function(){if(!k(q)){if(b.top===b.self){if("object"===typeof PrivacyManagerAPI&&"function"===typeof PrivacyManagerAPI.callApi){pa("getConsent","advertising");return}}else if(b.postMessage&&"object"===typeof JSON){qa("getConsent","advertising");return}q=1}C()};pa=function(a,c){q=PrivacyManagerAPI.callApi(a,"quantserve.com",
J(),"truste.com",c);C()};qa=function(a,c){var d={PrivacyManagerAPI:{timestamp:(new Date).getTime(),action:a,self:"quantserve.com",domain:J(),authority:"truste.com",type:c}};if(b.addEventListener)b.addEventListener("message",K,!1);else if(b.attachEvent)b.attachEvent("onmessage",K);else{q=!0;C();return}try{b.top.postMessage(JSON.stringify(d),"*")}catch(e){}ia=setTimeout(function(){k(q)||(q=!0,C())},25)};K=function(a){var c=null;if(a.source===window.top){try{c="object"===typeof JSON&&JSON.parse(a.data)}catch(d){}c&&
"object"===typeof c.PrivacyManagerAPI&&(clearTimeout(ia),b.removeEventListener?window.removeEventListener("message",K,!1):b.detachEvent&&window.detachEvent("onmessage",K),q=c.PrivacyManagerAPI,C())}};ha=function(){var a=arguments,c,b;s([].slice.call(a));for(b=0;b<a.length;b++)c=a[b],v(c);y.length?L(y.slice(0)):G()};s=function(a){var c=da(a);if("array"===c)for(c=0;c<a.length;c++)s(a[c]);else"object"===c&&fa(a.qacct||b._qacct)};wa=function(){var a;b._qevents.length||b.ezt.length||"undefined"===typeof _qacct||
v({qacct:b._qacct});if(!w.evts){for(a in b._qevents)b._qevents.hasOwnProperty(a)&&v(b._qevents[a]);for(a in b.ezt)b.ezt.hasOwnProperty(a)&&v(b.ezt[a]);b._qevents={push:ha};b.ezt.push=function(){var a=arguments,d;if(k(b.queueManager))for(d=0;d<a.length;d++)b.queueManager.push(a[d]);else ha.apply(this,arguments)};w.evts=1}};R=function(){var a;k(b._qevents)||(b._qevents=[]);k(b.ezt)||(b.ezt=[]);b._qoptions&&(a=T(b._qoptions),s(b._qoptions),b._qevents.push(a),b._qoptions=null);b.qcdata&&(a=T(b.qcdata),
s(b.qcdata),b._qevents.push(a),b.qcdata=null);b.smarttagdata&&(a=T(b.smarttagdata),s(b.smarttagdata),b._qevents.push(a),b.smarttagdata=null);w.evts||(b._qevents.push=function(){s([].slice.call(arguments));L(y.slice(0));return[].push.apply(b._qevents,arguments)},b.ezt.push=function(){s([].slice.call(arguments));L(y.slice(0));return[].push.apply(b.ezt,arguments)});s(b.ezt);s(b._qevents);s({qacct:b._qacct});b._qoptions=null;y.length?L(y.slice(0)):G();N=!0};b.quantserve=b.quantserve||R;w.quantserve=R;
return w}(window);
try{__qc("hasRules","p-WRMnQ6CenTfwQ")||function(b,l,z){try{__qc("defaults",b,{labels:"_fp.event.Default"})}catch(B){}var N=function(b,n,l){return b?"nc"===b?!n||!l||0>n.indexOf(l):"eq"===b?n===l:"sw"===b?0===n.indexOf(l):"ew"===b?(b=n.length-l.length,n=n.lastIndexOf(l,b),-1!==n&&n===b):"c"===b?0<=n.indexOf(l):!1:!1};__qc("rules",[b,null,[[function(b){return"array"==={}.toString.call(b).match(/\s([a-zA-Z]+)/)[1].toLowerCase()?{labels:b.join(",")}:{labels:""+b}},"_fp.event.Homepage"]],[[function(b,
n,D){var u;if(l.top===l.self)u=z.location.href;else{u=z.referrer;var B=z.createElement("a");B.href=u;u=B.href}N(n,u,D)?b(u):b(!1)},"eq","https://generalassemb.ly"]]])}("p-WRMnQ6CenTfwQ",window,document)}catch(nfe$$4){}quantserve();try{window.smarttagdata&&window._qevents.push(window.smarttagdata),window.qcdata&&window._qevents.push(window.qcdata)}catch(nfe$$5){};